const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const C=window.APP_CONFIG||{};
let sb=null,student=null,studentToken=null,semesters=[],teacherSemesterId=null,currentTeacherTab='semester';
const configured=C.SUPABASE_URL&&!String(C.SUPABASE_URL).startsWith('PASTE_')&&C.SUPABASE_PUBLISHABLE_KEY&&!String(C.SUPABASE_PUBLISHABLE_KEY).startsWith('PASTE_');
if(configured) sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY); else $('#setupNotice').classList.remove('hidden');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function msg(el,t,ok=false){if(!el)return;el.textContent=t;el.className=ok?'ok':'bad'}
function fmt(n,d=2){const x=Number(n||0);return Number.isFinite(x)?x.toFixed(d):'0.00'}
function weekOpts(selected=1){return Array.from({length:15},(_,i)=>`<option value="${i+1}" ${i+1===Number(selected)?'selected':''}>${i+1}주차</option>`).join('')}
function setMode(m){$('#studentSection').classList.toggle('hidden',m!=='s');$('#teacherSection').classList.toggle('hidden',m!=='t');$('#studentMode').classList.toggle('active',m==='s');$('#teacherMode').classList.toggle('active',m==='t');if(m==='t')tryRestoreTeacher()}
$('#studentMode').onclick=()=>setMode('s');$('#teacherMode').onclick=()=>setMode('t');

async function loadActiveSemesterPublic(){if(!sb)return;const {data}=await sb.rpc('c1_get_active_semester');$('#publicSemesterLabel').textContent=data?.ok?`${data.name} · 학생용 QR 하나로 접속`:'활성 학기가 없습니다.'}

// ---------------- 학생 ----------------
function saveStudentSession(){if(student&&studentToken)localStorage.setItem('c1_student_v2',JSON.stringify({student,token:studentToken}))}
function clearStudentSession(){localStorage.removeItem('c1_student_v2');student=null;studentToken=null}
async function restoreStudent(){if(!sb)return;try{const x=JSON.parse(localStorage.getItem('c1_student_v2')||'null');if(!x?.token)return;const {data}=await sb.rpc('c1_student_me',{p_token:x.token});if(data?.ok){student={id:data.id,login_no:data.login_no,name:data.name,semester_id:data.semester_id,semester_name:data.semester_name};studentToken=x.token;openStudentApp()}else clearStudentSession()}catch(e){clearStudentSession()}}
function openStudentApp(){$('#loginCard').classList.add('hidden');$('#studentApp').classList.remove('hidden');$('#who').textContent=`${student.login_no}번 ${student.name} · ${student.semester_name}`;renderAttendance();renderQuiz();renderFinal();renderHomework();renderScores();processHomeworkLink()}
$('#loginBtn').onclick=async()=>{if(!sb)return;const iid=Number($('#sid').value),name=$('#sname').value.trim();if(!Number.isInteger(iid)||iid<1||!name){msg($('#loginMsg'),'번호와 이름을 입력하세요.');return}const {data,error}=await sb.rpc('c1_student_login',{p_id:iid,p_name:name});if(error||!data?.ok){msg($('#loginMsg'),data?.message||'번호와 이름이 일치하지 않습니다.');return}student={id:data.id,login_no:data.login_no,name:data.name,semester_id:data.semester_id,semester_name:data.semester_name};studentToken=data.token;saveStudentSession();openStudentApp()}
$('#logoutBtn').onclick=async()=>{if(sb&&studentToken)await sb.rpc('c1_student_logout',{p_token:studentToken});clearStudentSession();$('#studentApp').classList.add('hidden');$('#loginCard').classList.remove('hidden')}
$$('#stabs button').forEach(b=>b.onclick=()=>{$$('#stabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.spane').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.tab+'Pane').classList.remove('hidden');if(b.dataset.tab==='scores')renderScores()});

async function renderAttendance(){if(!studentToken)return;$('#attendancePane').innerHTML=`<div class="card"><h3 class="section-title">출석 단어 입력</h3><div class="grid g2"><label>주차<select id="aw">${weekOpts()}</select></label><label>교시<select id="ap"><option value="1">1교시</option><option value="2">2교시</option><option value="3">3교시</option></select></label></div><label style="display:block;margin-top:10px">제시 단어<input id="attword" placeholder="시작 또는 종료 단어"></label><button id="attsub" class="primary" style="margin-top:10px">출석 확인</button><div id="attmsg" class="muted" style="margin-top:8px"></div><div id="attweekstatus" style="margin-top:12px"></div></div>`;const refresh=async()=>{const {data}=await sb.rpc('c1_get_attendance_week',{p_token:studentToken,p_week:Number($('#aw').value)});$('#attweekstatus').innerHTML=`<div class="grid g3">${(data||[]).map(x=>`<div class="q"><b>${x.period}교시</b><div>${esc(x.status)}</div></div>`).join('')}</div>`};$('#aw').onchange=refresh;$('#attsub').onclick=async()=>{const {data,error}=await sb.rpc('c1_check_attendance',{p_token:studentToken,p_week:Number($('#aw').value),p_period:Number($('#ap').value),p_word:$('#attword').value.trim()});$('#attword').value='';if(error||!data?.ok)msg($('#attmsg'),data?.message||error?.message||'확인 실패');else{msg($('#attmsg'),data.kind==='start'?'시작 출석 확인 완료':'종료 출석 확인 완료',true);refresh();renderScores()}};refresh()}

async function renderQuiz(){if(!studentToken)return;const {data}=await sb.rpc('c1_list_open_quizzes',{p_token:studentToken});$('#quizPane').innerHTML=`<div class="card"><h3 class="section-title">듣기평가</h3>${(data||[]).length?(data||[]).map(q=>`<div class="q"><div class="row"><b>제${q.round}차 · ${q.total}문항</b>${q.submitted?`<span class="ok">제출완료 ${q.score}/${q.total}</span><button data-qresult="${q.id}">정답·오답 보기</button>`:`<button data-q="${q.id}" data-total="${q.total}" class="primary">응시</button>`}</div><div id="qarea${q.id}"></div></div>`).join(''):'<div class="muted">현재 공개된 시험이 없습니다.</div>'}</div>`;$('#quizPane').querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>showExam(b.dataset.q,Number(b.dataset.total),false));$('#quizPane').querySelectorAll('[data-qresult]').forEach(b=>b.onclick=()=>showQuizResult(Number(b.dataset.qresult)))}
function questionUI(n,prefix){return Array.from({length:n},(_,i)=>`<div class="q"><b>${i+1}번</b><div class="choices">${['A','B','C','D'].map(c=>`<label class="choice"><input type="radio" name="${prefix}${i}" value="${c}">${c}</label>`).join('')}</div></div>`).join('')}
function collect(n,prefix){const a=[];for(let i=0;i<n;i++){const c=document.querySelector(`input[name="${prefix}${i}"]:checked`);if(!c)return null;a.push(c.value)}return a}
function result(r,ans){return `<div class="score">${r.score}/${r.total}점</div>${ans.map((a,i)=>`<div>${i+1}번: 선택 ${esc(a)} ${a===r.correct[i]?'✅':`❌ → 정답 <b>${esc(r.correct[i])}</b>`}</div>`).join('')}`}
function showExam(qid,n,isFinal){const area=isFinal?$('#finalPane'):$('#qarea'+qid),prefix=isFinal?'f-':`q${qid}-`;area.innerHTML=(isFinal?'<div class="card"><h3>기말고사 20문항</h3>':'')+questionUI(n,prefix)+`<button id="submitCurrent" class="primary">최종 제출</button><div id="exammsg" style="margin-top:10px"></div>`+(isFinal?'</div>':'');$('#submitCurrent').onclick=async()=>{const ans=collect(n,prefix);if(!ans){msg($('#exammsg'),'모든 문항에 답하세요.');return}const r=isFinal?await sb.rpc('c1_submit_final',{p_token:studentToken,p_answers:ans}):await sb.rpc('c1_submit_quiz',{p_token:studentToken,p_quiz_id:Number(qid),p_answers:ans});if(r.error||!r.data?.ok){msg($('#exammsg'),r.data?.message||r.error?.message||'제출 실패');return}area.innerHTML=`<div class="card">${isFinal?`<div><b>30점 환산: ${fmt(r.data.converted)} / 30</b></div>`:''}${result(r.data,ans)}</div>`;renderScores()}}
async function showQuizResult(qid){const {data,error}=await sb.rpc('c1_get_quiz_result',{p_token:studentToken,p_quiz_id:qid});if(error||!data?.ok)return;$('#qarea'+qid).innerHTML=`<div class="card">${result(data,data.answers)}</div>`}
async function renderFinal(){if(!studentToken)return;const {data}=await sb.rpc('c1_get_final_status',{p_token:studentToken});if(data?.submitted){$('#finalPane').innerHTML=`<div class="card"><h3>기말고사</h3><div class="ok">제출완료 · ${data.score}/20 · ${fmt(data.converted)}/30</div>${result(data,data.answers)}</div>`}else if(data?.open){$('#finalPane').innerHTML='<div class="card"><button id="startFinal" class="primary">기말고사 시작</button></div>';$('#startFinal').onclick=()=>showExam(1,20,true)}else $('#finalPane').innerHTML='<div class="card muted">기말고사가 아직 공개되지 않았습니다.</div>'}
function renderHomework(){if(!studentToken)return;$('#homeworkPane').innerHTML=`<div class="card"><h3 class="section-title">과제 확인</h3><div class="grid g2"><label>주차<select id="hwweek">${weekOpts()}</select></label><label>QR 인증코드<input id="hwcode"></label></div><button id="hwsub" class="primary" style="margin-top:10px">과제 확인</button><div id="hwmsg" class="muted" style="margin-top:8px"></div></div>`;$('#hwsub').onclick=async()=>submitHomework(Number($('#hwweek').value),$('#hwcode').value.trim(),$('#hwmsg'))}
async function submitHomework(week,code,el){const {data,error}=await sb.rpc('c1_check_homework',{p_token:studentToken,p_week:week,p_code:code});if(error||!data?.ok)msg(el,data?.message||error?.message||'실패');else{msg(el,'과제가 확인되었습니다.',true);renderScores()}}
async function processHomeworkLink(){const u=new URL(location.href),w=Number(u.searchParams.get('homework_week')),code=u.searchParams.get('code');if(!w||!code||!studentToken)return;$$('#stabs button').forEach(x=>x.classList.remove('active'));const b=$('#stabs [data-tab="homework"]');if(b)b.classList.add('active');$$('.spane').forEach(x=>x.classList.add('hidden'));$('#homeworkPane').classList.remove('hidden');renderHomework();setTimeout(()=>{if($('#hwweek'))$('#hwweek').value=String(w);if($('#hwcode'))$('#hwcode').value=code;submitHomework(w,code,$('#hwmsg'));history.replaceState({},'',location.pathname)},50)}
async function renderScores(){if(!studentToken)return;const {data}=await sb.rpc('c1_get_student_summary',{p_token:studentToken});if(!data?.ok)return;$('#scoresPane').innerHTML=`<div class="card"><h3 class="section-title">내 성적</h3><div class="grid g2"><div class="q"><div class="muted">듣기평가 → 중간</div><div class="score">${fmt(data.midterm)} / 30</div><div>${data.quiz_got}/${data.quiz_max}</div></div><div class="q"><div class="muted">출석</div><div class="score">${fmt(data.attendance,3)} / 20</div><div>결석 ${data.absent_periods}교시 · 지각 ${data.late_periods} · 조퇴 ${data.early_periods}</div></div><div class="q"><div class="muted">과제</div><div class="score">${fmt(data.homework_score)} / 20</div><div>${data.homework_done}/${data.homework_total}</div></div><div class="q"><div class="muted">기말고사</div><div class="score">${fmt(data.final_score)} / 30</div><div>${data.final_raw}/20</div></div></div><div class="q"><b>현재 총점</b><div class="score">${fmt(data.total)} / 100</div></div></div>`}

// ---------------- 교수자 ----------------
$('#teacherLoginBtn').onclick=async()=>{if(!sb)return;const {error}=await sb.auth.signInWithPassword({email:$('#temail').value.trim(),password:$('#tpassword').value});if(error){msg($('#teacherMsg'),error.message);return}await openTeacherApp()}
$('#teacherLogoutBtn').onclick=async()=>{if(sb)await sb.auth.signOut();$('#teacherApp').classList.add('hidden');$('#teacherLogin').classList.remove('hidden');$('#tpassword').value=''}
async function tryRestoreTeacher(){if(!sb||!$('#teacherApp').classList.contains('hidden'))return;const {data}=await sb.auth.getSession();if(data?.session)await openTeacherApp()}
async function openTeacherApp(){const ok=await loadSemesters();if(!ok){await sb.auth.signOut();msg($('#teacherMsg'),'교수자 권한을 확인할 수 없습니다.');return}$('#teacherLogin').classList.add('hidden');$('#teacherApp').classList.remove('hidden');renderTeacherTab(currentTeacherTab)}
async function loadSemesters(){const {data,error}=await sb.from('c1_semesters').select('id,name,is_active,created_at').order('id',{ascending:false});if(error)return false;semesters=data||[];if(!semesters.length)return false;if(!teacherSemesterId||!semesters.some(s=>String(s.id)===String(teacherSemesterId))){const active=semesters.find(s=>s.is_active);teacherSemesterId=active?.id||semesters[0]?.id||null}const sel=$('#semesterSelect');sel.innerHTML=semesters.map(s=>`<option value="${s.id}" ${String(s.id)===String(teacherSemesterId)?'selected':''}>${esc(s.name)}${s.is_active?' ★':''}</option>`).join('');sel.onchange=()=>{teacherSemesterId=Number(sel.value);updateSemesterBadge();renderTeacherTab(currentTeacherTab)};updateSemesterBadge();return true}
function selectedSemester(){return semesters.find(s=>String(s.id)===String(teacherSemesterId))}
function activeSemester(){return semesters.find(s=>s.is_active)}
function updateSemesterBadge(){const s=selectedSemester();$('#semesterBadge').textContent=s?(s.is_active?'현재 학생용 활성 학기':'과거/준비 학기'):''}
$$('#ttabs button').forEach(b=>b.onclick=()=>{$$('#ttabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tpane').forEach(x=>x.classList.add('hidden'));$('#t'+b.dataset.tab).classList.remove('hidden');currentTeacherTab=b.dataset.tab;renderTeacherTab(currentTeacherTab)});
async function renderTeacherTab(tab){if(!teacherSemesterId&&tab!=='semester')return;const fn={semester:renderSemesterManager,qr:renderTeacherQR,attendance:renderTeacherAttendance,quiz:renderTeacherQuiz,final:renderTeacherFinal,homework:renderTeacherHomework,grades:renderTeacherGrades}[tab];if(fn)await fn()}

async function renderSemesterManager(){const pane=$('#tsemester');const s=selectedSemester();if(!s){pane.innerHTML='<div class="card">학기를 먼저 만들어 주세요.</div>';return}const {data:roster,error}=await sb.from('c1_students').select('id,login_no,name').eq('semester_id',s.id).order('login_no');if(error){pane.innerHTML=`<div class="card bad">${esc(error.message)}</div>`;return}pane.innerHTML=`
<div class="card"><h3 class="section-title">학기 관리</h3><div class="grid g2"><label>새 학기 이름<input id="newSemesterName" placeholder="예: 2027-1학기 중국어1"></label><label style="display:flex;align-items:center;gap:8px;padding-top:24px"><input id="makeActiveNow" type="checkbox" checked style="width:auto;min-height:auto"> 만든 즉시 학생용 활성 학기로 전환</label></div><button id="createSemesterBtn" class="primary" style="margin-top:10px">새 학기 만들기</button><div id="semesterMsg" class="muted" style="margin-top:8px"></div>${s.is_active?'':`<div class="q"><b>${esc(s.name)}</b>은 현재 학생이 접속하는 학기가 아닙니다. 준비가 끝났을 때 <button id="activateSemesterBtn" class="primary mini">이 학기를 활성화</button></div>`}</div>
<div class="card"><h3 class="section-title">${esc(s.name)} 학생 명단 · ${roster.length}명</h3><div class="muted">새 학기 시작 전에는 명단 전체교체가 가능합니다. 출석·시험·과제 기록이 생긴 뒤에는 전체교체를 막아 과거 성적을 보호합니다.</div><div class="grid g2" style="margin-top:10px"><div><label>명단 붙여넣기<textarea id="rosterText" placeholder="한 줄에 한 명씩 이름을 넣으세요.\n김민수\n이지현\n...\n\n번호,이름 형식도 가능합니다."></textarea></label><div class="toolbar" style="margin-top:8px"><label>CSV/TXT 불러오기<input id="rosterFile" type="file" accept=".csv,.txt,text/csv,text/plain"></label><button id="replaceRosterBtn" class="primary">명단 전체교체</button></div><div id="rosterMsg" class="muted" style="margin-top:8px"></div></div><div><div class="grid g2"><label>고유번호<input id="addLoginNo" type="number" min="1" placeholder="예: 81"></label><label>이름<input id="addStudentName" placeholder="학생 이름"></label></div><button id="addStudentBtn" style="margin-top:8px">학생 1명 추가</button><div id="addStudentMsg" class="muted" style="margin-top:8px"></div></div></div></div>
<div class="card"><div class="tablewrap"><table><thead><tr><th>고유번호</th><th>이름</th><th>수정</th><th>삭제</th></tr></thead><tbody>${roster.map(r=>`<tr><td>${r.login_no}</td><td><input data-name-id="${r.id}" value="${esc(r.name)}"></td><td><button class="mini" data-save-student="${r.id}">이름 저장</button></td><td><button class="mini danger" data-del-student="${r.id}">삭제</button></td></tr>`).join('')}</tbody></table></div></div>`;
$('#createSemesterBtn').onclick=async()=>{const name=$('#newSemesterName').value.trim();if(!name){msg($('#semesterMsg'),'학기 이름을 입력하세요.');return}const {data,error}=await sb.rpc('c1_create_semester',{p_name:name,p_make_active:$('#makeActiveNow').checked});if(error||!data?.ok){msg($('#semesterMsg'),error?.message||'생성 실패');return}teacherSemesterId=data.id;await loadSemesters();msg($('#semesterMsg'),'새 학기를 만들었습니다.',true);renderSemesterManager();loadActiveSemesterPublic()};
if($('#activateSemesterBtn'))$('#activateSemesterBtn').onclick=async()=>{if(!confirm(`${s.name}을 학생용 활성 학기로 전환할까요? 기존 학생 로그인은 종료됩니다.`))return;const {error}=await sb.rpc('c1_set_active_semester',{p_semester_id:s.id});if(error){alert(error.message);return}await loadSemesters();renderSemesterManager();loadActiveSemesterPublic()};
$('#rosterFile').onchange=async e=>{const f=e.target.files?.[0];if(f)$('#rosterText').value=await f.text()};
$('#replaceRosterBtn').onclick=async()=>{const names=parseRoster($('#rosterText').value);if(!names.length){msg($('#rosterMsg'),'명단을 입력하세요.');return}if(!confirm(`${s.name}의 학생 명단을 ${names.length}명으로 전체교체할까요?`))return;const {data,error}=await sb.rpc('c1_replace_roster',{p_semester_id:s.id,p_names:names});if(error||!data?.ok){msg($('#rosterMsg'),error?.message||'명단 교체 실패');return}msg($('#rosterMsg'),`${data.count}명으로 교체했습니다.`,true);renderSemesterManager()};
$('#addStudentBtn').onclick=async()=>{const login_no=Number($('#addLoginNo').value),name=$('#addStudentName').value.trim();if(!Number.isInteger(login_no)||login_no<1||!name){msg($('#addStudentMsg'),'고유번호와 이름을 입력하세요.');return}const {error}=await sb.from('c1_students').insert({semester_id:s.id,login_no,name});if(error){msg($('#addStudentMsg'),error.message);return}msg($('#addStudentMsg'),'학생을 추가했습니다.',true);renderSemesterManager()};
pane.querySelectorAll('[data-save-student]').forEach(btn=>btn.onclick=async()=>{const id=Number(btn.dataset.saveStudent),inp=pane.querySelector(`[data-name-id="${id}"]`),name=inp.value.trim();if(!name)return;const {error}=await sb.from('c1_students').update({name}).eq('id',id);if(error)alert(error.message);else btn.textContent='저장됨'});
pane.querySelectorAll('[data-del-student]').forEach(btn=>btn.onclick=async()=>{const id=Number(btn.dataset.delStudent);if(!confirm('이 학생을 삭제할까요? 기록이 있으면 삭제되지 않습니다.'))return;const {error}=await sb.rpc('c1_delete_student',{p_student_id:id});if(error)alert(error.message);else renderSemesterManager()});
}
function parseRoster(text){return String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).filter(line=>!/^\s*(번호|고유번호|순번)\s*[,\t]/.test(line)).map(line=>{const csv=line.match(/^\s*\d+\s*[,\t]\s*(.+)$/);if(csv)return csv[1].trim();const spaced=line.match(/^\s*\d+\s{2,}(.+)$/);if(spaced)return spaced[1].trim();return line}).filter(Boolean)}

async function renderTeacherQR(){const pane=$('#tqr'),active=activeSemester(),url=location.origin+location.pathname;pane.innerHTML=`<div class="card"><h3 class="section-title">학생 접속 QR</h3><div class="muted">학기 내내 같은 QR을 사용합니다. 학생은 자동으로 현재 활성 학기 <b>${esc(active?.name||'없음')}</b>에 로그인합니다.</div><div id="mainQR" class="qrbox" style="margin-top:10px"></div><div style="margin-top:8px;word-break:break-all">${esc(url)}</div></div>`;new QRCode($('#mainQR'),{text:url,width:190,height:190})}

function attendanceStatus(rec,finalized){if(rec?.start_ok&&rec?.end_ok)return'출석';if(!rec?.start_ok&&rec?.end_ok)return'지각';if(rec?.start_ok&&!rec?.end_ok)return finalized?'조퇴':'시작 확인';return finalized?'결석':'미확인'}
async function renderTeacherAttendance(){const pane=$('#tattendance'),sem=selectedSemester();pane.innerHTML=`<div class="card"><h3 class="section-title">${esc(sem.name)} 출석 설정</h3><label style="max-width:220px;display:block">주차<select id="taWeek">${weekOpts()}</select></label><div id="taBody" style="margin-top:10px"></div></div>`;const load=async()=>{const w=Number($('#taWeek').value);const [{data:week},{data:words},{data:roster},{data:records}]=await Promise.all([sb.from('c1_attendance_weeks').select('*').eq('semester_id',sem.id).eq('week',w).single(),sb.from('c1_attendance_words').select('*').eq('semester_id',sem.id).eq('week',w).order('period'),sb.from('c1_students').select('id,login_no,name').eq('semester_id',sem.id).order('login_no'),sb.from('c1_attendance_records').select('student_id,period,start_ok,end_ok').eq('semester_id',sem.id).eq('week',w)]);const byP={};(words||[]).forEach(x=>byP[x.period]=x);const map=new Map((records||[]).map(r=>[`${r.student_id}-${r.period}`,r]));$('#taBody').innerHTML=`<div class="grid g3">${[1,2,3].map(p=>`<div class="q"><b>${p}교시</b><label>시작 단어<input data-aw-start="${p}" value="${esc(byP[p]?.start_word||'')}"></label><label>종료 단어<input data-aw-end="${p}" value="${esc(byP[p]?.end_word||'')}"></label></div>`).join('')}</div><div class="toolbar"><button id="saveWords" class="primary">6개 단어 저장</button><button id="finalizeWeek" class="${week?.finalized?'':'primary'}">${week?.finalized?'출석 확정 취소':'이 주차 출석 확정'}</button><span class="badge">${week?.finalized?'확정 완료':'아직 미확정'}</span></div><div id="taMsg" class="muted" style="margin-top:8px"></div><div class="tablewrap" style="margin-top:12px"><table><thead><tr><th>번호</th><th>이름</th><th>1교시</th><th>2교시</th><th>3교시</th></tr></thead><tbody>${(roster||[]).map(st=>`<tr><td>${st.login_no}</td><td>${esc(st.name)}</td>${[1,2,3].map(p=>`<td>${attendanceStatus(map.get(`${st.id}-${p}`),!!week?.finalized)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;$('#saveWords').onclick=async()=>{const rows=[1,2,3].map(p=>({semester_id:sem.id,week:w,period:p,start_word:$(`[data-aw-start="${p}"]`).value.trim(),end_word:$(`[data-aw-end="${p}"]`).value.trim()}));if(rows.some(r=>r.start_word&&r.start_word===r.end_word)){msg($('#taMsg'),'같은 교시의 시작·종료 단어는 다르게 입력하세요.');return}const {error}=await sb.from('c1_attendance_words').upsert(rows,{onConflict:'semester_id,week,period'});if(error)msg($('#taMsg'),error.message);else msg($('#taMsg'),'출석 단어 6개를 저장했습니다.',true)};$('#finalizeWeek').onclick=async()=>{if(!week?.finalized&&!confirm(`${w}주차 출석을 확정할까요? 미입력 교시는 결석으로 기록됩니다.`))return;const {error}=await sb.rpc('c1_set_attendance_week_finalized',{p_semester_id:sem.id,p_week:w,p_finalized:!week?.finalized});if(error)alert(error.message);else load()}};$('#taWeek').onchange=load;load()}

async function renderTeacherQuiz(){const pane=$('#tquiz'),sem=selectedSemester();const {data:qs,error}=await sb.from('c1_quizzes').select('*').eq('semester_id',sem.id).order('round');if(error){pane.innerHTML=`<div class="card bad">${esc(error.message)}</div>`;return}const maxRound=(qs||[]).reduce((m,q)=>Math.max(m,q.round),0);pane.innerHTML=`<div class="card"><div class="row"><div><h3 class="section-title">${esc(sem.name)} 듣기평가</h3><div class="muted">각 회차 5~6문항, 문항당 1점. 반영된 회차의 누적 원점수를 중간고사 30점으로 환산합니다.</div></div><button id="addQuizBtn" class="primary">제${maxRound+1}차 추가</button></div></div>${(qs||[]).map(q=>quizEditor(q)).join('')||'<div class="card muted">아직 만든 듣기평가가 없습니다.</div>'}`;$('#addQuizBtn').onclick=async()=>{const {error}=await sb.from('c1_quizzes').insert({semester_id:sem.id,round:maxRound+1,answer_key:['A','A','A','A','A'],is_open:false,counted:true});if(error)alert(error.message);else renderTeacherQuiz()};pane.querySelectorAll('[data-save-quiz]').forEach(btn=>btn.onclick=async()=>{const id=Number(btn.dataset.saveQuiz),card=btn.closest('.card'),count=Number(card.querySelector('[data-qcount]').value),answers=[...card.querySelectorAll('[data-qans]')].slice(0,count).map(x=>x.value);const {error}=await sb.from('c1_quizzes').update({answer_key:answers,is_open:card.querySelector('[data-qopen]').checked,counted:card.querySelector('[data-qcounted]').checked}).eq('id',id);if(error)alert(error.message);else{btn.textContent='저장됨';setTimeout(()=>btn.textContent='설정 저장',900)}})}
function quizEditor(q){const vals=[...q.answer_key];while(vals.length<6)vals.push('A');return `<div class="card"><div class="row"><h3 style="margin:0">제${q.round}차</h3><div class="toolbar"><label>문항 수<select data-qcount><option value="5" ${q.answer_key.length===5?'selected':''}>5</option><option value="6" ${q.answer_key.length===6?'selected':''}>6</option></select></label><label style="display:flex;align-items:center;gap:6px"><input data-qopen type="checkbox" style="width:auto;min-height:auto" ${q.is_open?'checked':''}> 학생에게 공개</label><label style="display:flex;align-items:center;gap:6px"><input data-qcounted type="checkbox" style="width:auto;min-height:auto" ${q.counted?'checked':''}> 중간고사 반영</label></div></div><div class="ansgrid" style="margin-top:10px">${vals.map((a,i)=>`<label>${i+1}번${i===5?' (6문항 시)':''}<select data-qans>${['A','B','C','D'].map(c=>`<option ${a===c?'selected':''}>${c}</option>`).join('')}</select></label>`).join('')}</div><button data-save-quiz="${q.id}" class="primary" style="margin-top:10px">설정 저장</button></div>`}

async function renderTeacherFinal(){const pane=$('#tfinal'),sem=selectedSemester();let {data:f,error}=await sb.from('c1_final_exam').select('*').eq('semester_id',sem.id).maybeSingle();if(error){pane.innerHTML=`<div class="card bad">${esc(error.message)}</div>`;return}if(!f){const d=['A','B','C','D','A','B','C','D','A','B','C','D','A','B','C','D','A','B','C','D'];await sb.from('c1_final_exam').insert({semester_id:sem.id,answer_key:d,is_open:false});f={semester_id:sem.id,answer_key:d,is_open:false}}pane.innerHTML=`<div class="card"><div class="row"><div><h3 class="section-title">${esc(sem.name)} 기말고사</h3><div class="muted">20문항 × 1점 = 원점수 20점 → 최종성적 30점 환산</div></div><label style="display:flex;align-items:center;gap:6px"><input id="finalOpen" type="checkbox" style="width:auto;min-height:auto" ${f.is_open?'checked':''}> 학생에게 공개</label></div><div class="ansgrid" style="margin-top:10px">${f.answer_key.map((a,i)=>`<label>${i+1}번<select data-fans>${['A','B','C','D'].map(c=>`<option ${a===c?'selected':''}>${c}</option>`).join('')}</select></label>`).join('')}</div><button id="saveFinal" class="primary" style="margin-top:10px">20문항 정답·공개 설정 저장</button><div id="finalMsg" class="muted" style="margin-top:8px"></div></div>`;$('#saveFinal').onclick=async()=>{const answer_key=[...pane.querySelectorAll('[data-fans]')].map(x=>x.value),is_open=$('#finalOpen').checked;const {error}=await sb.from('c1_final_exam').upsert({semester_id:sem.id,answer_key,is_open},{onConflict:'semester_id'});if(error)msg($('#finalMsg'),error.message);else msg($('#finalMsg'),'기말고사 설정을 저장했습니다.',true)}}

async function renderTeacherHomework(){const pane=$('#thomework'),sem=selectedSemester();pane.innerHTML=`<div class="card"><h3 class="section-title">${esc(sem.name)} 과제</h3><label style="max-width:220px;display:block">주차<select id="thwWeek">${weekOpts()}</select></label><div id="thwBody" style="margin-top:10px"></div></div>`;const load=async()=>{const w=Number($('#thwWeek').value);const [{data:h},{data:roster},{data:recs}]=await Promise.all([sb.from('c1_homework').select('*').eq('semester_id',sem.id).eq('week',w).maybeSingle(),sb.from('c1_students').select('id,login_no,name').eq('semester_id',sem.id),sb.from('c1_homework_records').select('student_id').eq('semester_id',sem.id).eq('week',w)]);const code=h?.code||'';const confirmed=new Set((recs||[]).map(x=>x.student_id));$('#thwBody').innerHTML=`<div class="grid g2"><label>인증코드<input id="hwTeacherCode" value="${esc(code)}" placeholder="자동생성 또는 직접 입력"></label><div class="toolbar"><button id="genHwCode">코드 자동생성</button><label style="display:flex;align-items:center;gap:6px"><input id="hwOpen" type="checkbox" style="width:auto;min-height:auto" ${h?.is_open?'checked':''}> 학생에게 공개</label><label style="display:flex;align-items:center;gap:6px"><input id="hwCounted" type="checkbox" style="width:auto;min-height:auto" ${h?.counted!==false?'checked':''}> 성적 반영</label></div></div><button id="saveHw" class="primary" style="margin-top:10px">과제 설정 저장</button><div id="hwTeacherMsg" class="muted" style="margin-top:8px"></div><div class="q"><b>확인 현황: ${confirmed.size}/${(roster||[]).length}명</b></div><div id="hwQR"></div>`;$('#genHwCode').onclick=()=>{$('#hwTeacherCode').value=`HW${String(w).padStart(2,'0')}-${Math.random().toString(36).slice(2,8).toUpperCase()}`};$('#saveHw').onclick=async()=>{const code=$('#hwTeacherCode').value.trim();if(!code){msg($('#hwTeacherMsg'),'인증코드를 입력하세요.');return}const row={semester_id:sem.id,week:w,code,is_open:$('#hwOpen').checked,counted:$('#hwCounted').checked};const {error}=await sb.from('c1_homework').upsert(row,{onConflict:'semester_id,week'});if(error)msg($('#hwTeacherMsg'),error.message);else{msg($('#hwTeacherMsg'),'과제 설정을 저장했습니다.',true);drawHomeworkQR(w,code,sem.is_active);}};if(code)drawHomeworkQR(w,code,sem.is_active)};$('#thwWeek').onchange=load;load()}
function drawHomeworkQR(week,code,isActive){const box=$('#hwQR');if(!box)return;const url=new URL(location.origin+location.pathname);url.searchParams.set('homework_week',week);url.searchParams.set('code',code);box.innerHTML=`<div class="muted">${isActive?'학생에게 보여줄 과제 QR':'이 학기는 현재 활성 학기가 아니므로 QR은 보관용입니다.'}</div><div id="hwQRImg" class="qrbox" style="margin-top:8px"></div><div class="muted" style="word-break:break-all;margin-top:6px">${esc(url.href)}</div>`;new QRCode($('#hwQRImg'),{text:url.href,width:180,height:180})}

async function renderTeacherGrades(){const pane=$('#tgrades'),sem=selectedSemester();pane.innerHTML='<div class="card">성적 계산 중…</div>';const {data,error}=await sb.rpc('c1_teacher_gradebook',{p_semester_id:sem.id});if(error){pane.innerHTML=`<div class="card bad">${esc(error.message)}</div>`;return}const rows=data||[],avg=k=>rows.length?rows.reduce((s,r)=>s+Number(r[k]||0),0)/rows.length:0;pane.innerHTML=`<div class="card"><div class="row"><div><h3 class="section-title">${esc(sem.name)} 성적</h3><div class="muted">듣기 30 + 출석 20 + 과제 20 + 기말 30 = 100점</div></div><button id="downloadCsv" class="primary">CSV 내려받기</button></div><div class="grid g4" style="margin-top:12px"><div class="stat"><div class="muted">학생 수</div><div class="n">${rows.length}명</div></div><div class="stat"><div class="muted">총점 평균</div><div class="n">${fmt(avg('total'))}</div></div><div class="stat"><div class="muted">중간 평균</div><div class="n">${fmt(avg('midterm'))}</div></div><div class="stat"><div class="muted">기말 환산 평균</div><div class="n">${fmt(avg('final_score'))}</div></div></div></div><div class="card"><div class="tablewrap"><table><thead><tr><th>번호</th><th>이름</th><th>듣기 원점수</th><th>중간/30</th><th>결석</th><th>지각</th><th>조퇴</th><th>출석/20</th><th>과제</th><th>과제/20</th><th>기말 원점수</th><th>기말/30</th><th>총점/100</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.login_no}</td><td>${esc(r.name)}</td><td>${r.quiz_got}/${r.quiz_max}</td><td>${fmt(r.midterm)}</td><td>${r.absent_periods}</td><td>${r.late_periods}</td><td>${r.early_periods}</td><td>${fmt(r.attendance,3)}</td><td>${r.homework_done}/${r.homework_total}</td><td>${fmt(r.homework_score)}</td><td>${r.final_raw}/20</td><td>${fmt(r.final_score)}</td><td><b>${fmt(r.total)}</b></td></tr>`).join('')}</tbody></table></div></div>`;$('#downloadCsv').onclick=()=>downloadGradeCsv(rows,sem.name)}
function downloadGradeCsv(rows,semesterName){const head=['번호','이름','듣기원점수','듣기만점','중간30','결석교시','지각','조퇴','출석20','과제완료','과제전체','과제20','기말원점수','기말30','총점100'];const lines=[head.join(','),...rows.map(r=>[r.login_no,csvCell(r.name),r.quiz_got,r.quiz_max,fmt(r.midterm),r.absent_periods,r.late_periods,r.early_periods,fmt(r.attendance,3),r.homework_done,r.homework_total,fmt(r.homework_score),r.final_raw,fmt(r.final_score),fmt(r.total)].join(','))];const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${semesterName}_성적.csv`;a.click();URL.revokeObjectURL(a.href)}
function csvCell(v){const s=String(v??'').replace(/"/g,'""');return `"${s}"`}

loadActiveSemesterPublic();restoreStudent();
