const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const C=window.APP_CONFIG||{};let sb=null,student=null,studentToken=null;
const configured=C.SUPABASE_URL&&!String(C.SUPABASE_URL).startsWith('PASTE_')&&C.SUPABASE_PUBLISHABLE_KEY&&!String(C.SUPABASE_PUBLISHABLE_KEY).startsWith('PASTE_');
if(configured) sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY); else $('#setupNotice').classList.remove('hidden');
function msg(el,t,ok=false){el.textContent=t;el.className=ok?'ok':'bad'}
function setMode(m){$('#studentSection').classList.toggle('hidden',m!=='s');$('#teacherSection').classList.toggle('hidden',m!=='t');$('#studentMode').classList.toggle('active',m==='s');$('#teacherMode').classList.toggle('active',m==='t')}
$('#studentMode').onclick=()=>setMode('s');$('#teacherMode').onclick=()=>setMode('t');
function saveStudentSession(){if(student&&studentToken){localStorage.setItem('c1_student',JSON.stringify({student,token:studentToken}))}}
function clearStudentSession(){localStorage.removeItem('c1_student');student=null;studentToken=null}
async function restoreStudent(){if(!sb)return;try{const x=JSON.parse(localStorage.getItem('c1_student')||'null');if(!x?.token)return;const {data}=await sb.rpc('student_me',{p_token:x.token});if(data?.ok){student={id:data.id,name:data.name};studentToken=x.token;openStudentApp();}else clearStudentSession()}catch(e){clearStudentSession()}}
function openStudentApp(){$('#loginCard').classList.add('hidden');$('#studentApp').classList.remove('hidden');$('#who').textContent=`${student.id}번 ${student.name}`;renderAttendance();renderQuiz();renderFinal();renderHomework();renderScores();processHomeworkLink()}
$('#loginBtn').onclick=async()=>{if(!sb)return;const iid=Number($('#sid').value),name=$('#sname').value.trim();if(!Number.isInteger(iid)||iid<1||!name){msg($('#loginMsg'),'번호와 이름을 입력하세요.');return}const {data,error}=await sb.rpc('student_login',{p_id:iid,p_name:name});if(error||!data?.ok){msg($('#loginMsg'),'번호와 이름이 일치하지 않습니다.');return}student={id:data.id,name:data.name};studentToken=data.token;saveStudentSession();openStudentApp()};
$('#logoutBtn').onclick=async()=>{if(sb&&studentToken)await sb.rpc('student_logout',{p_token:studentToken});clearStudentSession();$('#studentApp').classList.add('hidden');$('#loginCard').classList.remove('hidden')};
$$('#stabs button').forEach(b=>b.onclick=()=>{$$('#stabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.spane').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.tab+'Pane').classList.remove('hidden');if(b.dataset.tab==='scores')renderScores()});
function weekOpts(){return Array.from({length:15},(_,i)=>`<option value="${i+1}">${i+1}주차</option>`).join('')}
async function renderAttendance(){if(!studentToken)return;$('#attendancePane').innerHTML=`<div class="card"><h3>출석 단어 입력</h3><div class="grid g2"><label>주차<select id="aw">${weekOpts()}</select></label><label>교시<select id="ap"><option value="1">1교시</option><option value="2">2교시</option><option value="3">3교시</option></select></label></div><label style="display:block;margin-top:10px">제시 단어<input id="attword" placeholder="시작 또는 종료 단어"></label><button id="attsub" class="primary" style="margin-top:10px">출석 확인</button><div id="attmsg" class="muted" style="margin-top:8px"></div><div id="attweekstatus" style="margin-top:12px"></div></div>`;const refresh=async()=>{const {data}=await sb.rpc('get_attendance_week',{p_token:studentToken,p_week:Number($('#aw').value)});$('#attweekstatus').innerHTML=`<div class="grid g3">${(data||[]).map(x=>`<div class="q"><b>${x.period}교시</b><div>${x.status}</div></div>`).join('')}</div>`};$('#aw').onchange=refresh;$('#attsub').onclick=async()=>{const {data,error}=await sb.rpc('check_attendance',{p_token:studentToken,p_week:Number($('#aw').value),p_period:Number($('#ap').value),p_word:$('#attword').value.trim()});$('#attword').value='';if(error||!data?.ok)msg($('#attmsg'),data?.message||error?.message||'확인 실패');else{msg($('#attmsg'),data.kind==='start'?'시작 출석 확인 완료':'종료 출석 확인 완료',true);refresh();renderScores()}};refresh()}
async function renderQuiz(){if(!studentToken)return;const {data}=await sb.rpc('list_open_quizzes',{p_token:studentToken});$('#quizPane').innerHTML=`<div class="card"><h3>듣기평가</h3>${(data||[]).length?(data||[]).map(q=>`<div class="q"><div class="row"><b>제${q.round}차 · ${q.total}문항</b>${q.submitted?`<span class="ok">제출완료 ${q.score}/${q.total}</span><button data-qresult="${q.id}">정답·오답 보기</button>`:`<button data-q="${q.id}" data-total="${q.total}" class="primary">응시</button>`}</div><div id="qarea${q.id}"></div></div>`).join(''):'<div class="muted">현재 공개된 시험이 없습니다.</div>'}</div>`;$('#quizPane').querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>showExam(b.dataset.q,Number(b.dataset.total),false));$('#quizPane').querySelectorAll('[data-qresult]').forEach(b=>b.onclick=()=>showQuizResult(Number(b.dataset.qresult)))}
function questionUI(n,prefix){return Array.from({length:n},(_,i)=>`<div class="q"><b>${i+1}번</b><div class="choices">${['A','B','C','D'].map(c=>`<label class="choice"><input type="radio" name="${prefix}${i}" value="${c}">${c}</label>`).join('')}</div></div>`).join('')}
function collect(n,prefix){let a=[];for(let i=0;i<n;i++){let c=document.querySelector(`input[name="${prefix}${i}"]:checked`);if(!c)return null;a.push(c.value)}return a}
function result(r,ans){return `<div class="score">${r.score}/${r.total}점</div>${ans.map((a,i)=>`<div>${i+1}번: 선택 ${a} ${a===r.correct[i]?'✅':`❌ → 정답 <b>${r.correct[i]}</b>`}</div>`).join('')}`}
function showExam(qid,n,isFinal){const area=isFinal?$('#finalPane'):$('#qarea'+qid),prefix=isFinal?'f-':`q${qid}-`;area.innerHTML=(isFinal?'<div class="card"><h3>기말고사 20문항</h3>':'')+questionUI(n,prefix)+`<button id="submitCurrent" class="primary">최종 제출</button><div id="exammsg" style="margin-top:10px"></div>`+(isFinal?'</div>':'');$('#submitCurrent').onclick=async()=>{const ans=collect(n,prefix);if(!ans){msg($('#exammsg'),'모든 문항에 답하세요.');return}const r=isFinal?await sb.rpc('submit_final',{p_token:studentToken,p_answers:ans}):await sb.rpc('submit_quiz',{p_token:studentToken,p_quiz_id:Number(qid),p_answers:ans});if(r.error||!r.data?.ok){msg($('#exammsg'),r.data?.message||r.error?.message||'제출 실패');return}area.innerHTML=`<div class="card">${isFinal?`<div><b>30점 환산: ${Number(r.data.converted).toFixed(2)} / 30</b></div>`:''}${result(r.data,ans)}</div>`;renderScores()}}
async function showQuizResult(qid){const {data,error}=await sb.rpc('get_quiz_result',{p_token:studentToken,p_quiz_id:qid});if(error||!data?.ok)return;$('#qarea'+qid).innerHTML=`<div class="card">${result(data,data.answers)}</div>`}
async function renderFinal(){if(!studentToken)return;const {data}=await sb.rpc('get_final_status',{p_token:studentToken});if(data?.submitted){$('#finalPane').innerHTML=`<div class="card"><h3>기말고사</h3><div class="ok">제출완료 · ${data.score}/20 · ${Number(data.converted).toFixed(2)}/30</div>${result(data,data.answers)}</div>`}else if(data?.open){$('#finalPane').innerHTML='<div class="card"><button id="startFinal" class="primary">기말고사 시작</button></div>';$('#startFinal').onclick=()=>showExam(1,20,true)}else $('#finalPane').innerHTML='<div class="card muted">기말고사가 아직 공개되지 않았습니다.</div>'}
function renderHomework(){if(!studentToken)return;$('#homeworkPane').innerHTML=`<div class="card"><h3>과제 확인</h3><div class="grid g2"><label>주차<select id="hwweek">${weekOpts()}</select></label><label>QR 인증코드<input id="hwcode"></label></div><button id="hwsub" class="primary" style="margin-top:10px">과제 확인</button><div id="hwmsg" class="muted" style="margin-top:8px"></div></div>`;$('#hwsub').onclick=async()=>{await submitHomework(Number($('#hwweek').value),$('#hwcode').value.trim(),$('#hwmsg'))}}
async function submitHomework(week,code,el){const {data,error}=await sb.rpc('check_homework',{p_token:studentToken,p_week:week,p_code:code});if(error||!data?.ok)msg(el,data?.message||error?.message||'실패');else{msg(el,'과제가 확인되었습니다.',true);renderScores()}}
async function processHomeworkLink(){const u=new URL(location.href),w=Number(u.searchParams.get('homework_week')),code=u.searchParams.get('code');if(!w||!code||!studentToken)return;$$('#stabs button').forEach(x=>x.classList.remove('active'));const b=$('#stabs [data-tab="homework"]');if(b)b.classList.add('active');$$('.spane').forEach(x=>x.classList.add('hidden'));$('#homeworkPane').classList.remove('hidden');renderHomework();setTimeout(()=>{if($('#hwweek'))$('#hwweek').value=String(w);if($('#hwcode'))$('#hwcode').value=code;submitHomework(w,code,$('#hwmsg'));history.replaceState({},'',location.pathname)},50)}
async function renderScores(){if(!studentToken)return;const {data}=await sb.rpc('get_student_summary',{p_token:studentToken});if(!data?.ok)return;$('#scoresPane').innerHTML=`<div class="card"><h3>내 성적</h3><div class="grid g2"><div class="q"><div class="muted">듣기평가 → 중간</div><div class="score">${Number(data.midterm).toFixed(2)} / 30</div><div>${data.quiz_got}/${data.quiz_max}</div></div><div class="q"><div class="muted">출석</div><div class="score">${Number(data.attendance).toFixed(3)} / 20</div><div>결석 ${data.absent_periods}교시</div></div><div class="q"><div class="muted">과제</div><div class="score">${Number(data.homework_score).toFixed(2)} / 20</div><div>${data.homework_done}/${data.homework_total}</div></div><div class="q"><div class="muted">기말고사</div><div class="score">${Number(data.final_score).toFixed(2)} / 30</div><div>${data.final_raw}/20</div></div></div><div class="q"><b>현재 총점</b><div class="score">${Number(data.total).toFixed(2)} / 100</div></div></div>`}

$('#teacherLoginBtn').onclick=async()=>{if(!sb)return;const {error}=await sb.auth.signInWithPassword({email:$('#temail').value.trim(),password:$('#tpassword').value});if(error){msg($('#teacherMsg'),error.message);return}$('#teacherLogin').classList.add('hidden');$('#teacherApp').classList.remove('hidden');renderTeacherQR();renderTeacherAttendance();renderTeacherQuiz();renderTeacherFinal();renderTeacherHomework();renderGrades()};
$$('#ttabs button').forEach(b=>b.onclick=()=>{$$('#ttabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tpane').forEach(x=>x.classList.add('hidden'));$('#t'+b.dataset.tab).classList.remove('hidden');if(b.dataset.tab==='grades')renderGrades();if(b.dataset.tab==='qr')renderTeacherQR()});
function baseURL(){return location.origin+location.pathname}
function renderTeacherQR(){$('#tqr').innerHTML=`<div class="card"><h3>학생 접속 QR</h3><div class="muted">학기 내내 같은 QR을 사용할 수 있습니다.</div><div id="mainqr" class="qrbox" style="margin-top:12px"></div><div style="word-break:break-all;margin-top:8px">${baseURL()}</div></div>`;if(window.QRCode)new QRCode($('#mainqr'),{text:baseURL(),width:200,height:200})}
async function renderTeacherAttendance(){$('#tattendance').innerHTML=`<div class="card"><div class="row"><h3>출석 설정</h3><label style="min-width:150px">주차<select id="tw">${weekOpts()}</select></label></div><div id="weekstate" class="muted"></div><div id="wordedit"></div></div>`;const ed=async()=>{const w=Number($('#tw').value);const [{data},{data:wstate}]=await Promise.all([sb.from('attendance_words').select('*').eq('week',w),sb.from('attendance_weeks').select('*').eq('week',w).single()]);const map=Object.fromEntries((data||[]).map(x=>[x.period,x]));$('#weekstate').innerHTML=`현재 상태: <b>${wstate?.finalized?'출석 확정':'입력 가능'}</b> <button id="toggleFinalize">${wstate?.finalized?'확정 취소':'주차 출석 확정'}</button>`;$('#wordedit').innerHTML=[1,2,3].map(p=>`<div class="q"><b>${p}교시</b><div class="grid g2"><label>시작 단어<input data-s="${p}" value="${map[p]?.start_word||''}"></label><label>종료 단어<input data-e="${p}" value="${map[p]?.end_word||''}"></label></div></div>`).join('')+`<button id="savewords" class="primary">6개 단어 저장</button><div id="savemsg" class="muted"></div>`;$('#savewords').onclick=async()=>{let rows=[1,2,3].map(p=>({week:w,period:p,start_word:document.querySelector(`[data-s="${p}"]`).value.trim(),end_word:document.querySelector(`[data-e="${p}"]`).value.trim()}));const {error}=await sb.from('attendance_words').upsert(rows);if(error)msg($('#savemsg'),error.message);else msg($('#savemsg'),'저장 완료',true)};$('#toggleFinalize').onclick=async()=>{if(!wstate?.finalized&&!confirm(`${w}주차를 확정하면 미입력 교시는 결석으로 처리됩니다. 확정할까요?`))return;const {error}=await sb.rpc('set_attendance_week_finalized',{p_week:w,p_finalized:!wstate?.finalized});if(error)alert(error.message);ed();renderGrades()}};$('#tw').onchange=ed;ed()}
async function renderTeacherQuiz(){const {data}=await sb.from('quizzes').select('*').order('round');$('#tquiz').innerHTML=`<div class="card"><h3>듣기평가 설정</h3><div class="muted">5~6문항, 문항당 1점. 전체 누적 원점수를 30점으로 환산합니다.</div>${(data||[]).map(q=>`<div class="q"><div class="row"><b>제${q.round}차 · ${q.answer_key.length}문항</b><button data-toggleq="${q.id}">${q.is_open?'비공개':'공개'}</button></div><div class="muted">정답 ${q.answer_key.join(' · ')}</div></div>`).join('')}<button id="addQuiz" class="primary">새 듣기평가 만들기</button><div id="newq"></div></div>`;$('#tquiz').querySelectorAll('[data-toggleq]').forEach(b=>b.onclick=async()=>{const q=(data||[]).find(x=>String(x.id)===b.dataset.toggleq);await sb.from('quizzes').update({is_open:!q.is_open}).eq('id',q.id);renderTeacherQuiz()});$('#addQuiz').onclick=()=>{$('#newq').innerHTML=`<div class="q"><div class="grid g2"><label>회차<input id="qround" type="number" min="1"></label><label>문항수<select id="qcount"><option>5</option><option>6</option></select></label></div><div id="keyarea"></div><button id="saveq" class="primary">저장</button></div>`;const keys=()=>{$('#keyarea').innerHTML=Array.from({length:Number($('#qcount').value)},(_,i)=>`<label>${i+1}번<select data-key="${i}"><option>A</option><option>B</option><option>C</option><option>D</option></select></label>`).join('')};$('#qcount').onchange=keys;keys();$('#saveq').onclick=async()=>{const k=[...$('#keyarea').querySelectorAll('[data-key]')].map(x=>x.value),round=Number($('#qround').value);if(!round)return;const {error}=await sb.from('quizzes').insert({round,answer_key:k,is_open:false,counted:true});if(error)alert(error.message);else renderTeacherQuiz()}}}
async function renderTeacherFinal(){const {data}=await sb.from('final_exam').select('*').eq('id',1).single();$('#tfinal').innerHTML=`<div class="card"><div class="row"><div><h3>기말고사</h3><div class="muted">20문항 · 원점수 20점 → 30점 환산</div></div><button id="toggleFinal">${data?.is_open?'비공개':'공개'}</button></div><div id="fkey" class="grid g3" style="margin-top:12px">${(data?.answer_key||[]).map((a,i)=>`<label>${i+1}번<select data-fkey="${i}">${['A','B','C','D'].map(c=>`<option ${c===a?'selected':''}>${c}</option>`).join('')}</select></label>`).join('')}</div><button id="saveFinalKey" class="primary" style="margin-top:10px">정답 저장</button></div>`;$('#toggleFinal').onclick=async()=>{await sb.from('final_exam').update({is_open:!data.is_open}).eq('id',1);renderTeacherFinal()};$('#saveFinalKey').onclick=async()=>{const k=[...$('#fkey').querySelectorAll('[data-fkey]')].map(x=>x.value);const {error}=await sb.from('final_exam').update({answer_key:k}).eq('id',1);if(error)alert(error.message);else alert('기말고사 정답 저장 완료')}}
function randomCode(w){return `HW${String(w).padStart(2,'0')}-${Math.random().toString(36).slice(2,8).toUpperCase()}`}
async function renderTeacherHomework(){$('#thomework').innerHTML=`<div class="card"><h3>과제 설정</h3><div class="grid g2"><label>주차<select id="hww">${weekOpts()}</select></label><label>인증코드<input id="hwc"></label></div><div class="row" style="margin-top:10px"><label><input id="hwo" type="checkbox"> 공개</label><button id="makecode">코드 자동생성</button><button id="savehw" class="primary">저장</button></div><div id="thwmsg"></div><div id="hwqrwrap" class="hidden"><h4>학생용 과제 QR</h4><div id="hwqr" class="qrbox"></div><div id="hwurl" class="muted" style="word-break:break-all"></div></div></div>`;const load=async()=>{const w=Number($('#hww').value);const {data}=await sb.from('homework').select('*').eq('week',w).maybeSingle();$('#hwc').value=data?.code||'';$('#hwo').checked=!!data?.is_open;renderHWQR()};const renderHWQR=()=>{const w=Number($('#hww').value),code=$('#hwc').value.trim();if(!code){$('#hwqrwrap').classList.add('hidden');return}const u=new URL(baseURL());u.searchParams.set('homework_week',w);u.searchParams.set('code',code);$('#hwqrwrap').classList.remove('hidden');$('#hwqr').innerHTML='';$('#hwurl').textContent=u.toString();if(window.QRCode)new QRCode($('#hwqr'),{text:u.toString(),width:200,height:200})};$('#hww').onchange=load;$('#makecode').onclick=()=>{$('#hwc').value=randomCode(Number($('#hww').value));renderHWQR()};$('#hwc').oninput=renderHWQR;$('#savehw').onclick=async()=>{const w=Number($('#hww').value),code=$('#hwc').value.trim();if(!code){msg($('#thwmsg'),'인증코드를 입력하세요.');return}const {error}=await sb.from('homework').upsert({week:w,code,is_open:$('#hwo').checked,counted:true});if(error)msg($('#thwmsg'),error.message);else{msg($('#thwmsg'),'저장 완료',true);renderHWQR();renderGrades()}};load()}
async function renderGrades(){const [{data:sts},{data:qs},{data:qsub},{data:att},{data:weeks},{data:hw},{data:hwr},{data:fs}]=await Promise.all([sb.from('students').select('*').order('id'),sb.from('quizzes').select('*').eq('counted',true),sb.from('quiz_submissions').select('*'),sb.from('attendance_records').select('*'),sb.from('attendance_weeks').select('*').eq('finalized',true),sb.from('homework').select('*').eq('counted',true),sb.from('homework_records').select('*'),sb.from('final_submissions').select('*')]);let quizMax=(qs||[]).reduce((a,q)=>a+q.answer_key.length,0),hwTotal=(hw||[]).length,fw=new Set((weeks||[]).map(x=>x.week));const rows=(sts||[]).map(s=>{let got=(qsub||[]).filter(x=>x.student_id===s.id).reduce((a,x)=>a+x.score,0),mid=quizMax?got/quizMax*30:0;let abs=(att||[]).filter(x=>x.student_id===s.id&&fw.has(x.week)&&!x.start_ok&&!x.end_ok).length,ap=Math.max(0,20-abs/3);let done=(hwr||[]).filter(x=>x.student_id===s.id&&(hw||[]).some(h=>h.week===x.week)).length,hws=hwTotal?done/hwTotal*20:0;let f=(fs||[]).find(x=>x.student_id===s.id),fin=f?f.score/20*30:0;return{...s,got,quizMax,mid,abs,ap,done,hwTotal,hws,fin,total:mid+ap+hws+fin}});$('#tgrades').innerHTML=`<div class="card"><div class="row"><h3>성적관리</h3><button id="downloadCSV">CSV 내려받기</button></div><div class="tablewrap"><table><thead><tr><th>번호</th><th>이름</th><th>듣기30</th><th>출석20</th><th>과제20</th><th>기말30</th><th>총점</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.id}</td><td>${r.name}</td><td>${r.mid.toFixed(2)}<br><span class="muted">${r.got}/${r.quizMax}</span></td><td>${r.ap.toFixed(3)}<br><span class="muted">결석 ${r.abs}</span></td><td>${r.hws.toFixed(2)}<br><span class="muted">${r.done}/${r.hwTotal}</span></td><td>${r.fin.toFixed(2)}</td><td><b>${r.total.toFixed(2)}</b></td></tr>`).join('')}</tbody></table></div></div>`;$('#downloadCSV').onclick=()=>{const lines=[['번호','이름','듣기30','출석20','과제20','기말30','총점'],...rows.map(r=>[r.id,r.name,r.mid.toFixed(2),r.ap.toFixed(3),r.hws.toFixed(2),r.fin.toFixed(2),r.total.toFixed(2)])];const csv='\ufeff'+lines.map(x=>x.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='중국어1_성적.csv';a.click();URL.revokeObjectURL(u)}}
restoreStudent();
